name: Build Windows Installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Choose a Python version

    - name: 3. Install Inno Setup
      uses: Minionguy/setup-inno-setup-action@v1.0.0

    - name: 4. Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 5. Build the executable with PyInstaller
      run: |
        pyinstaller --name="MergeResampleApp" --onefile --windowed --add-data="icon.ico;." run.py
        
    - name: 6. Build the installer with Inno Setup
      run: iscc installer.iss

    - name: 7. Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: merge-resample-service-installer
        path: Setup-MergeResampleService.exe